/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DetailedEvent {
  'id' : string,
  'additionalData' : [] | [string],
  'interactionType' : [] | [InteractionType],
  'deviceDetails' : [] | [string],
  'duration' : [] | [bigint],
  'context' : [] | [UsageContext],
  'pageDetails' : [] | [string],
  'source' : { 'app' : null } |
    { 'browser' : null },
  'tags' : Array<string>,
  'timestamp' : Time,
  'eventType' : string,
}
export interface Event {
  'id' : string,
  'duration' : [] | [bigint],
  'context' : [] | [UsageContext],
  'source' : { 'app' : null } |
    { 'browser' : null },
  'tags' : Array<string>,
  'timestamp' : Time,
  'eventType' : string,
}
export type InteractionType = { 'formSubmit' : null } |
  { 'uiChange' : null } |
  { 'contentView' : null } |
  { 'navigation' : null } |
  { 'userInput' : null } |
  { 'buttonClick' : null } |
  { 'appSpecific' : string };
export interface Recommendation {
  'title' : string,
  'urgencyLevel' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
  'historicalPerformance' : Array<bigint>,
  'confidenceScore' : bigint,
  'message' : string,
  'category' : string,
}
export interface RoutinePattern {
  'context' : UsageContext,
  'avgDuration' : bigint,
  'dayOfWeekDistribution' : {
    'tuesday' : bigint,
    'wednesday' : bigint,
    'saturday' : bigint,
    'thursday' : bigint,
    'sunday' : bigint,
    'friday' : bigint,
    'monday' : bigint,
  },
  'timeOfDayDistribution' : {
    'morning' : bigint,
    'evening' : bigint,
    'night' : bigint,
    'afternoon' : bigint,
  },
  'frequency' : bigint,
}
export type Time = bigint;
export type UsageContext = { 'social' : null } |
  { 'other' : string } |
  { 'entertainment' : null } |
  { 'work' : null } |
  { 'exercise' : null } |
  { 'study' : null };
export interface UserProfile {
  'familyName' : string,
  'projectCustomer' : string,
  'onboardingComplete' : boolean,
  'projectTeamMembers' : Array<string>,
  'givenName' : string,
  'company' : string,
  'companyRole' : string,
  'project' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDetailedEvent' : ActorMethod<[DetailedEvent], undefined>,
  'addRoutinePattern' : ActorMethod<[RoutinePattern], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAlertsByUrgency' : ActorMethod<
    [{ 'low' : null } | { 'high' : null } | { 'medium' : null }],
    Array<Recommendation>
  >,
  'getAllData' : ActorMethod<
    [],
    {
      'patterns' : Array<RoutinePattern>,
      'recommendations' : Array<Recommendation>,
      'events' : Array<Event>,
      'detailedEvents' : Array<DetailedEvent>,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryFrequency' : ActorMethod<[UsageContext], bigint>,
  'getCategoryPercentage' : ActorMethod<[UsageContext], bigint>,
  'getDetailedEvents' : ActorMethod<
    [[] | [UsageContext]],
    Array<DetailedEvent>
  >,
  'getEvents' : ActorMethod<[[] | [UsageContext]], Array<Event>>,
  'getPaginatedEvents' : ActorMethod<[bigint, bigint], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logEvent' : ActorMethod<[Event], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRecommendation' : ActorMethod<[Recommendation], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];