/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InteractionType = IDL.Variant({
  'formSubmit' : IDL.Null,
  'uiChange' : IDL.Null,
  'contentView' : IDL.Null,
  'navigation' : IDL.Null,
  'userInput' : IDL.Null,
  'buttonClick' : IDL.Null,
  'appSpecific' : IDL.Text,
});
export const UsageContext = IDL.Variant({
  'social' : IDL.Null,
  'other' : IDL.Text,
  'entertainment' : IDL.Null,
  'work' : IDL.Null,
  'exercise' : IDL.Null,
  'study' : IDL.Null,
});
export const Time = IDL.Int;
export const DetailedEvent = IDL.Record({
  'id' : IDL.Text,
  'additionalData' : IDL.Opt(IDL.Text),
  'interactionType' : IDL.Opt(InteractionType),
  'deviceDetails' : IDL.Opt(IDL.Text),
  'duration' : IDL.Opt(IDL.Nat),
  'context' : IDL.Opt(UsageContext),
  'pageDetails' : IDL.Opt(IDL.Text),
  'source' : IDL.Variant({ 'app' : IDL.Null, 'browser' : IDL.Null }),
  'tags' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'eventType' : IDL.Text,
});
export const RoutinePattern = IDL.Record({
  'context' : UsageContext,
  'avgDuration' : IDL.Nat,
  'dayOfWeekDistribution' : IDL.Record({
    'tuesday' : IDL.Nat,
    'wednesday' : IDL.Nat,
    'saturday' : IDL.Nat,
    'thursday' : IDL.Nat,
    'sunday' : IDL.Nat,
    'friday' : IDL.Nat,
    'monday' : IDL.Nat,
  }),
  'timeOfDayDistribution' : IDL.Record({
    'morning' : IDL.Nat,
    'evening' : IDL.Nat,
    'night' : IDL.Nat,
    'afternoon' : IDL.Nat,
  }),
  'frequency' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Recommendation = IDL.Record({
  'title' : IDL.Text,
  'urgencyLevel' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'historicalPerformance' : IDL.Vec(IDL.Nat),
  'confidenceScore' : IDL.Nat,
  'message' : IDL.Text,
  'category' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Opt(IDL.Nat),
  'context' : IDL.Opt(UsageContext),
  'source' : IDL.Variant({ 'app' : IDL.Null, 'browser' : IDL.Null }),
  'tags' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'eventType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'familyName' : IDL.Text,
  'projectCustomer' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'projectTeamMembers' : IDL.Vec(IDL.Text),
  'givenName' : IDL.Text,
  'company' : IDL.Text,
  'companyRole' : IDL.Text,
  'project' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDetailedEvent' : IDL.Func([DetailedEvent], [], []),
  'addRoutinePattern' : IDL.Func([RoutinePattern], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAlertsByUrgency' : IDL.Func(
      [
        IDL.Variant({
          'low' : IDL.Null,
          'high' : IDL.Null,
          'medium' : IDL.Null,
        }),
      ],
      [IDL.Vec(Recommendation)],
      ['query'],
    ),
  'getAllData' : IDL.Func(
      [],
      [
        IDL.Record({
          'patterns' : IDL.Vec(RoutinePattern),
          'recommendations' : IDL.Vec(Recommendation),
          'events' : IDL.Vec(Event),
          'detailedEvents' : IDL.Vec(DetailedEvent),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryFrequency' : IDL.Func([UsageContext], [IDL.Nat], ['query']),
  'getCategoryPercentage' : IDL.Func([UsageContext], [IDL.Nat], ['query']),
  'getDetailedEvents' : IDL.Func(
      [IDL.Opt(UsageContext)],
      [IDL.Vec(DetailedEvent)],
      ['query'],
    ),
  'getEvents' : IDL.Func([IDL.Opt(UsageContext)], [IDL.Vec(Event)], ['query']),
  'getPaginatedEvents' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logEvent' : IDL.Func([Event], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRecommendation' : IDL.Func([Recommendation], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InteractionType = IDL.Variant({
    'formSubmit' : IDL.Null,
    'uiChange' : IDL.Null,
    'contentView' : IDL.Null,
    'navigation' : IDL.Null,
    'userInput' : IDL.Null,
    'buttonClick' : IDL.Null,
    'appSpecific' : IDL.Text,
  });
  const UsageContext = IDL.Variant({
    'social' : IDL.Null,
    'other' : IDL.Text,
    'entertainment' : IDL.Null,
    'work' : IDL.Null,
    'exercise' : IDL.Null,
    'study' : IDL.Null,
  });
  const Time = IDL.Int;
  const DetailedEvent = IDL.Record({
    'id' : IDL.Text,
    'additionalData' : IDL.Opt(IDL.Text),
    'interactionType' : IDL.Opt(InteractionType),
    'deviceDetails' : IDL.Opt(IDL.Text),
    'duration' : IDL.Opt(IDL.Nat),
    'context' : IDL.Opt(UsageContext),
    'pageDetails' : IDL.Opt(IDL.Text),
    'source' : IDL.Variant({ 'app' : IDL.Null, 'browser' : IDL.Null }),
    'tags' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  const RoutinePattern = IDL.Record({
    'context' : UsageContext,
    'avgDuration' : IDL.Nat,
    'dayOfWeekDistribution' : IDL.Record({
      'tuesday' : IDL.Nat,
      'wednesday' : IDL.Nat,
      'saturday' : IDL.Nat,
      'thursday' : IDL.Nat,
      'sunday' : IDL.Nat,
      'friday' : IDL.Nat,
      'monday' : IDL.Nat,
    }),
    'timeOfDayDistribution' : IDL.Record({
      'morning' : IDL.Nat,
      'evening' : IDL.Nat,
      'night' : IDL.Nat,
      'afternoon' : IDL.Nat,
    }),
    'frequency' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Recommendation = IDL.Record({
    'title' : IDL.Text,
    'urgencyLevel' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'historicalPerformance' : IDL.Vec(IDL.Nat),
    'confidenceScore' : IDL.Nat,
    'message' : IDL.Text,
    'category' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Opt(IDL.Nat),
    'context' : IDL.Opt(UsageContext),
    'source' : IDL.Variant({ 'app' : IDL.Null, 'browser' : IDL.Null }),
    'tags' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'familyName' : IDL.Text,
    'projectCustomer' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'projectTeamMembers' : IDL.Vec(IDL.Text),
    'givenName' : IDL.Text,
    'company' : IDL.Text,
    'companyRole' : IDL.Text,
    'project' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDetailedEvent' : IDL.Func([DetailedEvent], [], []),
    'addRoutinePattern' : IDL.Func([RoutinePattern], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAlertsByUrgency' : IDL.Func(
        [
          IDL.Variant({
            'low' : IDL.Null,
            'high' : IDL.Null,
            'medium' : IDL.Null,
          }),
        ],
        [IDL.Vec(Recommendation)],
        ['query'],
      ),
    'getAllData' : IDL.Func(
        [],
        [
          IDL.Record({
            'patterns' : IDL.Vec(RoutinePattern),
            'recommendations' : IDL.Vec(Recommendation),
            'events' : IDL.Vec(Event),
            'detailedEvents' : IDL.Vec(DetailedEvent),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryFrequency' : IDL.Func([UsageContext], [IDL.Nat], ['query']),
    'getCategoryPercentage' : IDL.Func([UsageContext], [IDL.Nat], ['query']),
    'getDetailedEvents' : IDL.Func(
        [IDL.Opt(UsageContext)],
        [IDL.Vec(DetailedEvent)],
        ['query'],
      ),
    'getEvents' : IDL.Func(
        [IDL.Opt(UsageContext)],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getPaginatedEvents' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logEvent' : IDL.Func([Event], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRecommendation' : IDL.Func([Recommendation], [], []),
  });
};

export const init = ({ IDL }) => { return []; };