/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type InteractionType = {
    __kind__: "formSubmit";
    formSubmit: null;
} | {
    __kind__: "uiChange";
    uiChange: null;
} | {
    __kind__: "contentView";
    contentView: null;
} | {
    __kind__: "navigation";
    navigation: null;
} | {
    __kind__: "userInput";
    userInput: null;
} | {
    __kind__: "buttonClick";
    buttonClick: null;
} | {
    __kind__: "appSpecific";
    appSpecific: string;
};
export type Time = bigint;
export type UsageContext = {
    __kind__: "social";
    social: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "work";
    work: null;
} | {
    __kind__: "exercise";
    exercise: null;
} | {
    __kind__: "study";
    study: null;
};
export interface Event {
    id: string;
    duration?: bigint;
    context?: UsageContext;
    source: Variant_app_browser;
    tags: Array<string>;
    timestamp: Time;
    eventType: string;
}
export interface RoutinePattern {
    context: UsageContext;
    avgDuration: bigint;
    dayOfWeekDistribution: {
        tuesday: bigint;
        wednesday: bigint;
        saturday: bigint;
        thursday: bigint;
        sunday: bigint;
        friday: bigint;
        monday: bigint;
    };
    timeOfDayDistribution: {
        morning: bigint;
        evening: bigint;
        night: bigint;
        afternoon: bigint;
    };
    frequency: bigint;
}
export interface Recommendation {
    title: string;
    urgencyLevel: Variant_low_high_medium;
    historicalPerformance: Array<bigint>;
    confidenceScore: bigint;
    message: string;
    category: string;
}
export interface DetailedEvent {
    id: string;
    additionalData?: string;
    interactionType?: InteractionType;
    deviceDetails?: string;
    duration?: bigint;
    context?: UsageContext;
    pageDetails?: string;
    source: Variant_app_browser;
    tags: Array<string>;
    timestamp: Time;
    eventType: string;
}
export interface UserProfile {
    familyName: string;
    projectCustomer: string;
    onboardingComplete: boolean;
    projectTeamMembers: Array<string>;
    givenName: string;
    company: string;
    companyRole: string;
    project: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_app_browser {
    app = "app",
    browser = "browser"
}
export enum Variant_low_high_medium {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDetailedEvent(detailedEvent: DetailedEvent): Promise<void>;
    addRoutinePattern(pattern: RoutinePattern): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAlertsByUrgency(urgency: Variant_low_high_medium): Promise<Array<Recommendation>>;
    getAllData(): Promise<{
        patterns: Array<RoutinePattern>;
        recommendations: Array<Recommendation>;
        events: Array<Event>;
        detailedEvents: Array<DetailedEvent>;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryFrequency(category: UsageContext): Promise<bigint>;
    getCategoryPercentage(category: UsageContext): Promise<bigint>;
    getDetailedEvents(filter: UsageContext | null): Promise<Array<DetailedEvent>>;
    getEvents(filter: UsageContext | null): Promise<Array<Event>>;
    getPaginatedEvents(page: bigint, pageSize: bigint): Promise<Array<Event>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logEvent(event: Event): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitRecommendation(rec: Recommendation): Promise<void>;
}
import type { DetailedEvent as _DetailedEvent, Event as _Event, InteractionType as _InteractionType, Recommendation as _Recommendation, RoutinePattern as _RoutinePattern, Time as _Time, UsageContext as _UsageContext, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDetailedEvent(arg0: DetailedEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDetailedEvent(to_candid_DetailedEvent_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDetailedEvent(to_candid_DetailedEvent_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRoutinePattern(arg0: RoutinePattern): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoutinePattern(to_candid_RoutinePattern_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoutinePattern(to_candid_RoutinePattern_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAlertsByUrgency(arg0: Variant_low_high_medium): Promise<Array<Recommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsByUrgency(to_candid_variant_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsByUrgency(to_candid_variant_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllData(): Promise<{
        patterns: Array<RoutinePattern>;
        recommendations: Array<Recommendation>;
        events: Array<Event>;
        detailedEvents: Array<DetailedEvent>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllData();
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllData();
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryFrequency(arg0: UsageContext): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryFrequency(to_candid_UsageContext_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryFrequency(to_candid_UsageContext_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCategoryPercentage(arg0: UsageContext): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryPercentage(to_candid_UsageContext_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryPercentage(to_candid_UsageContext_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getDetailedEvents(arg0: UsageContext | null): Promise<Array<DetailedEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetailedEvents(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetailedEvents(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(arg0: UsageContext | null): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaginatedEvents(arg0: bigint, arg1: bigint): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedEvents(arg0, arg1);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedEvents(arg0, arg1);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logEvent(to_candid_Event_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logEvent(to_candid_Event_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitRecommendation(arg0: Recommendation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRecommendation(to_candid_Recommendation_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRecommendation(to_candid_Recommendation_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DetailedEvent_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetailedEvent): DetailedEvent {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_InteractionType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteractionType): InteractionType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RoutinePattern_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoutinePattern): RoutinePattern {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UsageContext_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsageContext): UsageContext {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UsageContext]): UsageContext | null {
    return value.length === 0 ? null : from_candid_UsageContext_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InteractionType]): InteractionType | null {
    return value.length === 0 ? null : from_candid_InteractionType_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    urgencyLevel: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    historicalPerformance: Array<bigint>;
    confidenceScore: bigint;
    message: string;
    category: string;
}): {
    title: string;
    urgencyLevel: Variant_low_high_medium;
    historicalPerformance: Array<bigint>;
    confidenceScore: bigint;
    message: string;
    category: string;
} {
    return {
        title: value.title,
        urgencyLevel: from_candid_variant_n16(_uploadFile, _downloadFile, value.urgencyLevel),
        historicalPerformance: value.historicalPerformance,
        confidenceScore: value.confidenceScore,
        message: value.message,
        category: value.category
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patterns: Array<_RoutinePattern>;
    recommendations: Array<_Recommendation>;
    events: Array<_Event>;
    detailedEvents: Array<_DetailedEvent>;
}): {
    patterns: Array<RoutinePattern>;
    recommendations: Array<Recommendation>;
    events: Array<Event>;
    detailedEvents: Array<DetailedEvent>;
} {
    return {
        patterns: from_candid_vec_n18(_uploadFile, _downloadFile, value.patterns),
        recommendations: from_candid_vec_n13(_uploadFile, _downloadFile, value.recommendations),
        events: from_candid_vec_n23(_uploadFile, _downloadFile, value.events),
        detailedEvents: from_candid_vec_n29(_uploadFile, _downloadFile, value.detailedEvents)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    context: _UsageContext;
    avgDuration: bigint;
    dayOfWeekDistribution: {
        tuesday: bigint;
        wednesday: bigint;
        saturday: bigint;
        thursday: bigint;
        sunday: bigint;
        friday: bigint;
        monday: bigint;
    };
    timeOfDayDistribution: {
        morning: bigint;
        evening: bigint;
        night: bigint;
        afternoon: bigint;
    };
    frequency: bigint;
}): {
    context: UsageContext;
    avgDuration: bigint;
    dayOfWeekDistribution: {
        tuesday: bigint;
        wednesday: bigint;
        saturday: bigint;
        thursday: bigint;
        sunday: bigint;
        friday: bigint;
        monday: bigint;
    };
    timeOfDayDistribution: {
        morning: bigint;
        evening: bigint;
        night: bigint;
        afternoon: bigint;
    };
    frequency: bigint;
} {
    return {
        context: from_candid_UsageContext_n21(_uploadFile, _downloadFile, value.context),
        avgDuration: value.avgDuration,
        dayOfWeekDistribution: value.dayOfWeekDistribution,
        timeOfDayDistribution: value.timeOfDayDistribution,
        frequency: value.frequency
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: [] | [bigint];
    context: [] | [_UsageContext];
    source: {
        app: null;
    } | {
        browser: null;
    };
    tags: Array<string>;
    timestamp: _Time;
    eventType: string;
}): {
    id: string;
    duration?: bigint;
    context?: UsageContext;
    source: Variant_app_browser;
    tags: Array<string>;
    timestamp: Time;
    eventType: string;
} {
    return {
        id: value.id,
        duration: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.duration)),
        context: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.context)),
        source: from_candid_variant_n28(_uploadFile, _downloadFile, value.source),
        tags: value.tags,
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    additionalData: [] | [string];
    interactionType: [] | [_InteractionType];
    deviceDetails: [] | [string];
    duration: [] | [bigint];
    context: [] | [_UsageContext];
    pageDetails: [] | [string];
    source: {
        app: null;
    } | {
        browser: null;
    };
    tags: Array<string>;
    timestamp: _Time;
    eventType: string;
}): {
    id: string;
    additionalData?: string;
    interactionType?: InteractionType;
    deviceDetails?: string;
    duration?: bigint;
    context?: UsageContext;
    pageDetails?: string;
    source: Variant_app_browser;
    tags: Array<string>;
    timestamp: Time;
    eventType: string;
} {
    return {
        id: value.id,
        additionalData: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.additionalData)),
        interactionType: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.interactionType)),
        deviceDetails: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.deviceDetails)),
        duration: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.duration)),
        context: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.context)),
        pageDetails: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.pageDetails)),
        source: from_candid_variant_n28(_uploadFile, _downloadFile, value.source),
        tags: value.tags,
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Variant_low_high_medium {
    return "low" in value ? Variant_low_high_medium.low : "high" in value ? Variant_low_high_medium.high : "medium" in value ? Variant_low_high_medium.medium : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    other: string;
} | {
    entertainment: null;
} | {
    work: null;
} | {
    exercise: null;
} | {
    study: null;
}): {
    __kind__: "social";
    social: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "work";
    work: null;
} | {
    __kind__: "exercise";
    exercise: null;
} | {
    __kind__: "study";
    study: null;
} {
    return "social" in value ? {
        __kind__: "social",
        social: value.social
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "entertainment" in value ? {
        __kind__: "entertainment",
        entertainment: value.entertainment
    } : "work" in value ? {
        __kind__: "work",
        work: value.work
    } : "exercise" in value ? {
        __kind__: "exercise",
        exercise: value.exercise
    } : "study" in value ? {
        __kind__: "study",
        study: value.study
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    app: null;
} | {
    browser: null;
}): Variant_app_browser {
    return "app" in value ? Variant_app_browser.app : "browser" in value ? Variant_app_browser.browser : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    formSubmit: null;
} | {
    uiChange: null;
} | {
    contentView: null;
} | {
    navigation: null;
} | {
    userInput: null;
} | {
    buttonClick: null;
} | {
    appSpecific: string;
}): {
    __kind__: "formSubmit";
    formSubmit: null;
} | {
    __kind__: "uiChange";
    uiChange: null;
} | {
    __kind__: "contentView";
    contentView: null;
} | {
    __kind__: "navigation";
    navigation: null;
} | {
    __kind__: "userInput";
    userInput: null;
} | {
    __kind__: "buttonClick";
    buttonClick: null;
} | {
    __kind__: "appSpecific";
    appSpecific: string;
} {
    return "formSubmit" in value ? {
        __kind__: "formSubmit",
        formSubmit: value.formSubmit
    } : "uiChange" in value ? {
        __kind__: "uiChange",
        uiChange: value.uiChange
    } : "contentView" in value ? {
        __kind__: "contentView",
        contentView: value.contentView
    } : "navigation" in value ? {
        __kind__: "navigation",
        navigation: value.navigation
    } : "userInput" in value ? {
        __kind__: "userInput",
        userInput: value.userInput
    } : "buttonClick" in value ? {
        __kind__: "buttonClick",
        buttonClick: value.buttonClick
    } : "appSpecific" in value ? {
        __kind__: "appSpecific",
        appSpecific: value.appSpecific
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recommendation>): Array<Recommendation> {
    return value.map((x)=>from_candid_Recommendation_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoutinePattern>): Array<RoutinePattern> {
    return value.map((x)=>from_candid_RoutinePattern_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DetailedEvent>): Array<DetailedEvent> {
    return value.map((x)=>from_candid_DetailedEvent_n30(_uploadFile, _downloadFile, x));
}
function to_candid_DetailedEvent_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DetailedEvent): _DetailedEvent {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_InteractionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): _InteractionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Recommendation_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recommendation): _Recommendation {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_RoutinePattern_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutinePattern): _RoutinePattern {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UsageContext_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsageContext): _UsageContext {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsageContext | null): [] | [_UsageContext] {
    return value === null ? candid_none() : candid_some(to_candid_UsageContext_n5(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    additionalData?: string;
    interactionType?: InteractionType;
    deviceDetails?: string;
    duration?: bigint;
    context?: UsageContext;
    pageDetails?: string;
    source: Variant_app_browser;
    tags: Array<string>;
    timestamp: Time;
    eventType: string;
}): {
    id: string;
    additionalData: [] | [string];
    interactionType: [] | [_InteractionType];
    deviceDetails: [] | [string];
    duration: [] | [bigint];
    context: [] | [_UsageContext];
    pageDetails: [] | [string];
    source: {
        app: null;
    } | {
        browser: null;
    };
    tags: Array<string>;
    timestamp: _Time;
    eventType: string;
} {
    return {
        id: value.id,
        additionalData: value.additionalData ? candid_some(value.additionalData) : candid_none(),
        interactionType: value.interactionType ? candid_some(to_candid_InteractionType_n3(_uploadFile, _downloadFile, value.interactionType)) : candid_none(),
        deviceDetails: value.deviceDetails ? candid_some(value.deviceDetails) : candid_none(),
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        context: value.context ? candid_some(to_candid_UsageContext_n5(_uploadFile, _downloadFile, value.context)) : candid_none(),
        pageDetails: value.pageDetails ? candid_some(value.pageDetails) : candid_none(),
        source: to_candid_variant_n7(_uploadFile, _downloadFile, value.source),
        tags: value.tags,
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration?: bigint;
    context?: UsageContext;
    source: Variant_app_browser;
    tags: Array<string>;
    timestamp: Time;
    eventType: string;
}): {
    id: string;
    duration: [] | [bigint];
    context: [] | [_UsageContext];
    source: {
        app: null;
    } | {
        browser: null;
    };
    tags: Array<string>;
    timestamp: _Time;
    eventType: string;
} {
    return {
        id: value.id,
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        context: value.context ? candid_some(to_candid_UsageContext_n5(_uploadFile, _downloadFile, value.context)) : candid_none(),
        source: to_candid_variant_n7(_uploadFile, _downloadFile, value.source),
        tags: value.tags,
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    urgencyLevel: Variant_low_high_medium;
    historicalPerformance: Array<bigint>;
    confidenceScore: bigint;
    message: string;
    category: string;
}): {
    title: string;
    urgencyLevel: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    historicalPerformance: Array<bigint>;
    confidenceScore: bigint;
    message: string;
    category: string;
} {
    return {
        title: value.title,
        urgencyLevel: to_candid_variant_n12(_uploadFile, _downloadFile, value.urgencyLevel),
        historicalPerformance: value.historicalPerformance,
        confidenceScore: value.confidenceScore,
        message: value.message,
        category: value.category
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    context: UsageContext;
    avgDuration: bigint;
    dayOfWeekDistribution: {
        tuesday: bigint;
        wednesday: bigint;
        saturday: bigint;
        thursday: bigint;
        sunday: bigint;
        friday: bigint;
        monday: bigint;
    };
    timeOfDayDistribution: {
        morning: bigint;
        evening: bigint;
        night: bigint;
        afternoon: bigint;
    };
    frequency: bigint;
}): {
    context: _UsageContext;
    avgDuration: bigint;
    dayOfWeekDistribution: {
        tuesday: bigint;
        wednesday: bigint;
        saturday: bigint;
        thursday: bigint;
        sunday: bigint;
        friday: bigint;
        monday: bigint;
    };
    timeOfDayDistribution: {
        morning: bigint;
        evening: bigint;
        night: bigint;
        afternoon: bigint;
    };
    frequency: bigint;
} {
    return {
        context: to_candid_UsageContext_n5(_uploadFile, _downloadFile, value.context),
        avgDuration: value.avgDuration,
        dayOfWeekDistribution: value.dayOfWeekDistribution,
        timeOfDayDistribution: value.timeOfDayDistribution,
        frequency: value.frequency
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_medium): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_medium.low ? {
        low: null
    } : value == Variant_low_high_medium.high ? {
        high: null
    } : value == Variant_low_high_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "formSubmit";
    formSubmit: null;
} | {
    __kind__: "uiChange";
    uiChange: null;
} | {
    __kind__: "contentView";
    contentView: null;
} | {
    __kind__: "navigation";
    navigation: null;
} | {
    __kind__: "userInput";
    userInput: null;
} | {
    __kind__: "buttonClick";
    buttonClick: null;
} | {
    __kind__: "appSpecific";
    appSpecific: string;
}): {
    formSubmit: null;
} | {
    uiChange: null;
} | {
    contentView: null;
} | {
    navigation: null;
} | {
    userInput: null;
} | {
    buttonClick: null;
} | {
    appSpecific: string;
} {
    return value.__kind__ === "formSubmit" ? {
        formSubmit: value.formSubmit
    } : value.__kind__ === "uiChange" ? {
        uiChange: value.uiChange
    } : value.__kind__ === "contentView" ? {
        contentView: value.contentView
    } : value.__kind__ === "navigation" ? {
        navigation: value.navigation
    } : value.__kind__ === "userInput" ? {
        userInput: value.userInput
    } : value.__kind__ === "buttonClick" ? {
        buttonClick: value.buttonClick
    } : value.__kind__ === "appSpecific" ? {
        appSpecific: value.appSpecific
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "social";
    social: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "work";
    work: null;
} | {
    __kind__: "exercise";
    exercise: null;
} | {
    __kind__: "study";
    study: null;
}): {
    social: null;
} | {
    other: string;
} | {
    entertainment: null;
} | {
    work: null;
} | {
    exercise: null;
} | {
    study: null;
} {
    return value.__kind__ === "social" ? {
        social: value.social
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "entertainment" ? {
        entertainment: value.entertainment
    } : value.__kind__ === "work" ? {
        work: value.work
    } : value.__kind__ === "exercise" ? {
        exercise: value.exercise
    } : value.__kind__ === "study" ? {
        study: value.study
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_app_browser): {
    app: null;
} | {
    browser: null;
} {
    return value == Variant_app_browser.app ? {
        app: null
    } : value == Variant_app_browser.browser ? {
        browser: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
